main/views/auth_views.py
import functools

from flask import Blueprint, redirect, url_for, request, flash, render_template, session, g
from werkzeug.security import generate_password_hash, check_password_hash

from main import db
from main.models import User
from main.forms import UserCreateForm, UserLoginForm

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        userid = User.query.filter_by(userid=form.userid.data).first()
        user = User.query.filter_by(username=form.username.data).first()
        phone = User.query.filter_by(phone=form.phone.data).first()
        if userid:
            flash('이미 존재하는 사용자 입니다..')
            return redirect(url_for('auth.signup'))
        if user:
            flash('이미 존재하는 닉네임 입니다..')
            return redirect(url_for('auth.signup'))
        if phone:
            flash('이미 존재하는 전화번호 입니다.')
            return redirect(url_for('auth.signup'))

        user = User(userid=form.userid.data,
                    username=form.username.data,
                    password=generate_password_hash(form.password1.data),
                    email=form.email.data,
                    phone=form.phone.data,
                    address=form.address.data
                    )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('auth/signup.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userid=form.userid.data).first()
        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 올바르지 않습니다.'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)  # GET 방식으로 로그인 요청시 html 문서가 나오도록


# 로그인한 사용자면 g.user에 유저 정보를 받아서 저장
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(int(user_id))


# 로그아웃시 session을 삭제하고 메인 으로 보냄
@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


# 특정 페이지에 로그인한 유저가 아니면 로그인페이지로 보냄
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)

    return wrapped_view

main/views/items_views.py
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, flash, url_for, redirect, g, current_app
import os
from main import db
from main.models import Product, ProductImage
from main.views.auth_views import login_required

bp = Blueprint('items', __name__, url_prefix='/items')


@bp.route('/main/')
def _main():
    event = Product.query.filter_by(tags='이벤트').all()
    clothing = Product.query.filter_by(tags='의류').all()
    accessory = Product.query.filter_by(tags='악세서리').all()
    misc = Product.query.filter_by(tags='잡화').all()

    return render_template('items/items_main.html', event=event, clothing=clothing, misc=misc, accessory=accessory)


@bp.route('/list/')
def _list():
    products = Product.query.order_by(Product.create_date.desc()).all()
    return render_template('items/items_list.html', products=products)


@bp.route('/create', methods=['GET', 'POST'])
@login_required  # 로그인한 사용자만 접근이 가능
def create():
    if request.method == 'POST':
        #  html 입력한 값 받아오기
        title = request.form['title']
        price = int(request.form.get('price') or 0)
        discount = request.form.get('discount')
        tags = request.form.get('tags')
        content = request.form.get('description', '내용없음')
        user_id = g.user.id

        #  DB 저장하기
        product = Product(
            title=title,
            content=content,  # content 필수 채움
            price=price,
            discount=discount,
            create_date=datetime.now(),
            tags=tags,
            user_id=user_id
        )
        db.session.add(product)
        db.session.commit()  # db 에 먼저 저장해서 product.id 확보

        files = request.files.getlist('images')  # 여러 이미지 가져오기
        upload_folder = os.path.join(current_app.root_path, 'static/product_img', str(g.user.id))  # 저장할 경로
        os.makedirs(upload_folder, exist_ok=True)  # 경로에 해당하는 파일이 없으면 생성

        for file in files:
            if file and file.filename != '':  # 파일 존재 확인
                filename = file.filename  # 안전한 파일명
                filepath = os.path.join(upload_folder, filename)  # 저장 경로
                file.save(filepath)  # 서버에 파일 저장

                product_image = ProductImage(
                    product_id=product.id,
                    img_path=f'product_img/{g.user.id}/{filename}'  # 저장하면서 경로에 userid추가
                )
                db.session.add(product_image)

        db.session.commit()
        flash('상품 등록 완료!', 'success')
        return redirect(url_for('items._list'))

    return render_template('items/items_form.html')


@bp.route('/detail/<int:product_id>')
def detail(product_id):
    weekday_map = {
        'Mon': '월',
        'Tue': '화',
        'Wed': '수',
        'Thu': '목',
        'Fri': '금',
        'Sat': '토',
        'Sun': '일'
    }
    today = datetime.today()
    arrival_date = datetime.today() + timedelta(days=2)
    today_weekday = weekday_map[today.strftime('%a')]
    weekday = weekday_map[arrival_date.strftime('%a')]
    today_formatted_date = today.strftime(f'%m.%d ({today_weekday})')
    formatted_date = arrival_date.strftime(f'%m.%d ({weekday})')

    products = Product.query.order_by(Product.create_date.desc()).all()
    product = Product.query.get_or_404(product_id)

    return render_template('items/items_detail.html', product=product, products=products, arrival=formatted_date,
                           today=today_formatted_date)


@bp.route('/delete/<int:product_id>')
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)

    # 작성자이거나 관리자이면 삭제 가능
    if g.user.id != product.user_id and not g.user.admin:
        flash('삭제 권한이 없습니다.', 'danger')
        return redirect(url_for('items._list'))

    # 상품 이미지 먼저 삭제
    ProductImage.query.filter_by(product_id=product.id).delete()

    # 상품 삭제
    db.session.delete(product)
    db.session.commit()
    flash('상품이 삭제되었습니다.', 'success')

    return redirect(url_for('member.mypage'))

main/templates/items/items_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>5PICK</title>

    <!-- 파일 연결 -->

    <link rel="stylesheet" href='{{ url_for("static", filename='detail/detail.css') }}'>
    <link rel="stylesheet" href="{{ url_for('static', filename='sub_css/sub_common.css') }}">

    <!-- fontawesome icon 연결 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

    <!-- js연결 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>

</head>
<body>
<!------------------------------------------------------>
<!-- header -->
<!------------------------------------------------------>
<header>
    <div class="head">
        <div class="logo">
            <a href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='img/main/찐막로고.png') }}"
                                                       alt="짝퉁로고"></a>
        </div>
        <div class="search">
            <input type="text" placeholder="검색어를 입력하세요">
            <button>검색</button>
        </div>
        <ul class="nav">
            {% if g.user %}
                <li><a href="{{ url_for('auth.logout') }}">로그아웃</a></li>
                <li><a href="{{ url_for('member.mypage') }}">마이페이지</a></li>
            {% else %}
                <li><a href="{{ url_for('auth.login') }}">로그인</a></li>
                <li><a href="{{ url_for('auth.signup') }}">회원가입</a></li>
            {% endif %}
            <li><a href="">고객지원</a></li>
        </ul>
    </div>
</header>
<!------------------------------------------------------>
<!-- title -->
<!------------------------------------------------------>
<div class="title">
    <div class="title-start">
        <div class="title-slide">
            <div class="swiper mySwiper2">
                <div class="swiper-wrapper">
                    {% for img in product.images %}
                        <div class="swiper-slide">
                            <!-- 첫 번째 이미지 -->
                            <img src="{{ url_for('static', filename=img.img_path) }}"
                                 alt="{{ product.title }}">
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
            <div thumbsSlider="" class="swiper mySwiper">
                <div class="swiper-wrapper">
                    {% for img in product.images %}
                        <div class="swiper-slide">
                            <!-- 첫 번째 이미지 -->
                            <img src="{{ url_for('static', filename=img.img_path) }}"
                                 alt="{{ product.title }}">
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="warning">
                <img src="{{ url_for('static', filename='img/detail/직거래_정보유출_보상_불가.png') }}" alt="개인정보 유출 시 보상 불가">
            </div>
        </div>
        <div class="title-sale">
            <div class="title-sale-1">
                <i class="fa-solid fa-gift"></i>
                <h3>지금 보고있는 상품과 <br>
                    같이 담으면 할인되는 <span>살수록 할인</span> 상품</h3>
            </div>
            <div class="title-sale-2">
                <button>살수록할인</button>
                <p>2개부터, <span>300원씩 추가할인</span></p>
            </div>
            <div class="title-sale-3">
                <img src="{{ url_for('static', filename='img/detail/잡화9-1.jpg') }}" alt="살수록할인">
                <div class="title-sale-4">
                    <p>냥이네 과수원 양모펠트 가방고리 키링</p>
                    <div class="title-sale-4-1">
                        <p><span>30%</span> 2,100원</p>
                    </div>
                    <div class="title-sale-4-2">
                        <p></p>
                        <p>4.3</p>
                        <p>(12)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="title-end">
        <h3>{{ product.title }}</h3>
        <div class="title-end-1">
            <button>당일배송</button>
        </div>
        <div class="title-end-text1">
            <p>★</p>
            <p>4.8</p>
            <p>후기 191개</p>
        </div>
        <p class="title-price">{{ "{:,}".format( product.price) if product.price is not none else '0' }}원</p>
        <div class="title-end-price">
            <span>{{ product.discount }}%</span>
            <p>{{ "{:,}".format( (product.price * (1 - product.discount / 100))|round(0)|int) if product.price is not none else '0' }}원</p>
        </div>
        <p class="title-end-text2">2,500원 최대적립</p>
        <div class="title-end-text3">
            <p>후기 적립</p>
            <p>2,500원</p>
        </div>
        <div class="title-bottom">
            <div class="title-good">
                <p>♡</p>
                <p>8.2천</p>
            </div>
            <div class="title-pocket">장바구니</div>
            <div class="title-buynow">바로 구매</div>
        </div>
        <div class="delivery">
            <div class="delivery-group">
                <button>예약배송</button>
                <p>{{ arrival }} 도착 예정</p>
            </div>
            <p>{{ today }} 출고 • 우체국택배</p>
            <p>재고에 따라 무배당발 또는 일반배송으로 발송되며, <br>
                주문 시 배송 방식을 확인할 수 있습니다.</p>
        </div>
        <div class="membership">
            <img src="{{ url_for('static', filename='img/detail/membership.png') }}" alt="멤버십 혜택">
        </div>
        <div class="other">
            <h2> 놓치면 아쉬운 <br> 이번 주 인기 작가님!</h2>
            <div class="other-all">
                <div class="other_autor active1">
                    <div class="plus">
                        <p>최근 440건 더 많이 구매되었어요!</p>
                    </div>
                    <img src="{{ url_for('static', filename='img/detail/작가1.png') }}" alt="작가1">
                    <div class="other-text">
                        <h3>자연을 연구하는 명인코스메틱</h3>
                        <div class="other-subtext">
                            <p>★</p>
                            <p>4.9</p>
                            <p>(1,732)</p>
                        </div>
                        <div class="coupon-button">쿠폰</div>
                    </div>
                </div>
                <div class="other_autor">
                    <div class="plus plus1">
                        <p>최근 267건 더 많이 구매되었어요!</p>
                    </div>
                    <img src="{{ url_for('static', filename='img/detail/작가2.png') }}" alt="작가2">
                    <div class="other-text">
                        <h3>덫밥 - The taste trap</h3>
                        <div class="other-subtext">
                            <p>★</p>
                            <p>4.7</p>
                            <p>(8,374)</p>
                        </div>
                        <div class="coupon-button">쿠폰</div>
                    </div>
                </div>
                <div class="other_autor">
                    <div class="plus plus2">
                        <p>최근 874건 더 많이 구매되었어요!</p>
                    </div>
                    <img src="{{ url_for('static', filename='img/detail/작가3.png') }}" alt="작가3">
                    <div class="other-text">
                        <h3>힙서리 - Hipseori</h3>
                        <div class="other-subtext">
                            <p>★</p>
                            <p>4.9</p>
                            <p>(910)</p>
                        </div>
                        <div class="coupon-button">쿠폰</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!------------------------------------------------------>
<!-- Review -->
<!------------------------------------------------------>
<div class="Review">
    <div class="Review-all">
        <img src="{{ url_for('static', filename='img/detail/리뷰이벤트.png') }}" alt="">
    </div>
</div>


<div class="footer">
    <div class="footer-all">
        <div class="footer-logo">
            <img src="{{ url_for('static', filename='img/main/찐찐찐막로고.png') }}" alt="">
        </div>
        <div class="footer-text">
            <div>
                <ul class="footer-text1">
                    <li>고객 안내</li>
                    <li>이용 안내</li>
                    <li>안전 정책</li>
                    <li>회사 소개</li>
                    <li>공지사항</li>
                    <li>자주 묻는 질문</li>
                </ul>
            </div>
            <div>
                <ul class="footer-text1">
                    <li>오핑몰 소개</li>
                    <li>회사 소개</li>
                    <li>채용 안내</li>
                    <li>팀 블로그</li>
                    <li>개인정보 처리방침</li>
                    <li>고객센터</li>
                </ul>
            </div>
            <div>
                <ul class="footer-text1">
                    <li>About Store</li>
                    <li>회사명(주) : 오핑몰</li>
                    <li>주소 : 경기도 수원시 팔달구 권광로 146 벽산그랜드코아 4층 404호</li>
                    <li>대표 : 김카피</li>
                    <li>사업자등록번호 : 012-34-56789</li>
                    <li>통신판매업 신고번호 : 012-345-6789</li>
                    <li>대표번호 : 010-1234-5678</li>
                    <li>메일주소 : 5pickshop@naver.com</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-sub">
        <div class="footer-sub-all">
            <div class="footer-icon">
                <a href="https://www.naver.com/"><img src="{{ url_for('static', filename='img/main/sub/naver.png') }}"
                                                      alt="naver_logo"></a>
                <a href="https://www.youtube.com/"><img
                        src="{{ url_for('static', filename='img/main/sub/youtube.png') }}" alt="youtube_logo"></a>
                <a href="https://www.instagram.com/"><img
                        src="{{ url_for('static', filename='img/main/sub/instar.png') }}" alt="instagram_logo"></a>
                <a href="https://www.facebook.com/"><img
                        src="{{ url_for('static', filename='img/main/sub/f-book.png') }}" alt="facebook_logo"></a>
                <a href="https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=ko"><img
                        src="{{ url_for('static', filename='img/main/sub/kotalk.png') }}" alt="kakao_logo"></a>
            </div>
            <p>Copyright © All Right Reserved</p>
            <div class="footer-card">
                <img src="{{ url_for('static', filename='img/main/card1.svg') }}" alt="카드1">
                <img src="{{ url_for('static', filename='img/main/card2.svg') }}" alt="카드2">
                <img src="{{ url_for('static', filename='img/main/card3.svg') }}" alt="카드3">
                <img src="{{ url_for('static', filename='img/main/card4.svg') }}" alt="카드4">
                <img src="{{ url_for('static', filename='img/main/card5.svg') }}" alt="카드5">
            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script src="{{ url_for('static', filename='detail/detail_slide.js') }}"></script>


</body>
</html>

main/templates/items/items_form.html
{% extends 'base.html' %}
{% block create %}

    <link rel="stylesheet" href="{{ url_for('static', filename='create/new.css') }}">
{% endblock %}
{% block content %}


    {# 코드 작성은 이선 이후로 작성 바람#}
    {# form 모든 입력을 하나로 묶어서 flask로 보낼 통로 #}
    <form method="post" action="{{ url_for('items.create') }}" enctype="multipart/form-data">
        <div id="slider1">
            <div class="new">
                <div class="new-button">상품등록</div>
            </div>
        </div>
        <!-- 몸통2 -->
        <div id="slider2">
            <div class="title">
                <div class="title-box">
                    <input type="text" name="title" placeholder="제목을 입력하세요.">
                </div>
            </div>
        </div>
        <!-- 몸통3 -->
        <div id="slider3">
            <div class="setting">
                <div class="title-setting">
                    <input type="text" name="discount" placeholder="할인율을 입력하세요. (숫자만 입력하세요.)">
                    <input type="text" name="price" placeholder="가격을 입력하세요. (숫자만 입력하세요.)">
                </div>
            </div>
        </div>

        <!-- 몸통4 -->
        <        <!-- 몸통4 -->

        <div id="slider4">
            <div class="category-box">
                <div class="category-text">
                    <h2>상품 카테고리 선택</h2>
                    <select id="categorySelect" name="tags">
                        <option value="">-- 카테고리를 선택하세요 --</option>
                        <option value="의류">👕 의류</option>
                        <option value="악세서리">💍 악세서리</option>
                        <option value="잡화">🧺 잡화</option>
                        <option value="이벤트">🎁 이벤트</option>
                    </select>
                </div>
                <div id="result"></div>
            </div>
        </div>
        <!-- 몸통5 -->
        <div id="slider5">
            <div class="new_image">
                <div class="nimg-up">
                    <label for="imageUpload">이미지 업로드</label>
                    <input type="file" name="images" multiple>
                </div>
            </div>
        </div>
        <!-- 몸통6 -->
        <div id="slider6">
            <div class="save">
                <div class="save_pu">
                    <input type="submit" value="저장하기" class="save_s">
                </div>
            </div>
        </div>
    </form>
{% endblock %}

main/templates/items/items_list.html
{% extends 'base.html' %}
{% block sub %}

    <link rel="stylesheet" href="{{ url_for('static', filename='sub_css/sub_index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='sub_css/sub_common.css') }}">

{% endblock %}

{% block content %}

    {# 코드 작성은 이선 이후로 작성 바람#}

    <!-- 위로 올라가기 버튼 - HTML -->
    <a href="#" id="back-to-top" class="back-to-top">▲</a>


    <div id="slider1">
        <!-- 필터 -->
        <div class="filter">
            <div class="filter-line">
                <h3 class="filter-title">FILTER</h3>
                <div class="filter-section">
                    <button class="filter-toggle">브랜드<span class="arrow">^</span></button>
                    <ul class="filter-list">
                        <li><input type="checkbox" id="brand1"><label for="brand1">카피바라</label></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- 몸통1-1 -->
        <div class="cont1">

            <!-- 사이즈 -->
            <div class="size">
                <div class="size-line">
                    <h3 class="size-title">SIZE</h3>
                    <div class="size-section">
                        <button class="size-toggle">사이즈<span class="arrow2">^</span></button>
                        <ul class="size-list">
                            <li><input type="checkbox" id="s"><label for="s">S</label></li>
                            <li><input type="checkbox" id="m"><label for="m">M</label></li>
                            <li><input type="checkbox" id="L"><label for="L">L</label></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="product-container">
                {% if products %}
                    {% for p in products %}
                        <div class="product-card-wrapper">
                            <a href="{{ url_for('items.detail', product_id=p.id) }}">
                                <div class="product-card" data-color="{{ p.color or 'default' }}">
                                    {% if p.images %}
                                        <!-- 첫 번째 이미지 -->
                                        <img src="{{ url_for('static', filename=p.images[0].img_path) }}"
                                             alt="{{ p.title }}">
                                    {% else %}
                                        <!-- 이미지 없으면 기본 이미지 -->
                                        <img src="{{ url_for('static', filename='product_img/상품기본.gif') }}"
                                             alt="{{ p.title }}">
                                    {% endif %}
                                    <h3>{{ p.title }}</h3>
                                    <div class="disa1">
                                        <span>{{ p.discount }}%</span>
                                        <p>{{ "{:,}".format( p.price) }}원</p>
                                    </div>
                                    <p class="discount">{{ "{:,}".format( (p.price * (1 - p.discount / 100))|round(0)|int) }}원</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p style="text-align:center; margin-top:50px;">등록된 상품이 없습니다.</p>
                {% endif %}

            </div>
        </div>
    </div>
    <!-- 몸통3 -->
    <div id="slider3">
        <!-- 몸통3-1 -->
        <div class="cont5">
            <div class="pull3"></div>
            <!-- 몸뚱아리 다섯줄 -->
            <div class="five">
                <div class="d1">
                    <h2>고객 리뷰</h2>
                    <p>실제 구매 고객들의 후기를 확인해보세요!</p>
                </div>
                <!-- 리뷰 요약 -->
                <div class="d2">
                    <h3>⭐ 4.8 / 5.0</h3>
                    <p>(총 1,245개의 리뷰)</p>
                </div>
                <!-- 리뷰 상세 -->
                <div class="d3">
                    <div class="review-card">
                        <h4>⭐⭐⭐⭐⭐</h4>
                        <p>"옷이 생각보다 훨씬 예뻐요! 배송도 빨랐습니다."</p>
                        <span> 사용자 ID</span>
                    </div>
                    <div class="review-card">
                        <h4>⭐⭐⭐⭐⭐</h4>
                        <p>"핏이 딱 맞고 친구들이 예쁘다고 칭찬했어요."</p>
                        <span> 사용자 ID</span>
                    </div>
                    <div class="review-card">
                        <h4>⭐⭐⭐⭐⭐</h4>
                        <p>"재질도 좋고 생각보다 편해서 만족합니다."</p>
                        <span> 사용자 ID</span>
                    </div>
                    <div class="review-card">
                        <h4>⭐⭐⭐⭐⭐</h4>
                        <p>"옷 예쁘고 맘에 들어요."</p>
                        <span>사용자 ID</span>
                    </div>
                </div>
            </div>
            <!-- 통계 -->
            <div class="review-extra">
                <h3>리뷰 통계</h3>
                <ul>
                    <li>⭐ 5점: 1020명</li>
                    <li>⭐ 4점: 180명</li>
                    <li>⭐ 3점: 30명</li>
                    <li>⭐ 2점: 10명</li>
                    <li>⭐ 1점: 5명</li>
                </ul>
                <h3 class="photo-review-all">베스트 포토 리뷰</h3>
                <div class="photo-reviews">
                    <img src="{{ url_for('static', filename='img/sub/이벤트.png') }}" alt="리뷰1">

                </div>
            </div>

        </div>
    </div>
    <script src="{{ url_for('static', filename='sub_js/color.js') }}"></script>
    <script src="{{ url_for('static', filename='sub_js/filter.js') }}"></script>
    <script src="{{ url_for('static', filename='sub_js/size.js') }}"></script>

{% endblock %}