main/views/items_views.py
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, flash, url_for, redirect, g, current_app
import os
from main import db
from main.models import Product, ProductImage
from main.views.auth_views import login_required

bp = Blueprint('items', __name__, url_prefix='/items')


@bp.route('/main/')
def _main():
    event = Product.query.filter_by(tags='이벤트').all()
    clothing = Product.query.filter_by(tags='의류').all()
    accessory = Product.query.filter_by(tags='악세서리').all()
    misc = Product.query.filter_by(tags='잡화').all()

    return render_template('items/items_main.html', event=event, clothing=clothing, misc=misc, accessory=accessory)


@bp.route('/list/')
def _list():
    products = Product.query.order_by(Product.create_date.desc()).all()
    return render_template('items/items_list.html', products=products)


@bp.route('/create', methods=['GET', 'POST'])
@login_required  # 로그인한 사용자만 접근이 가능
def create():
    if request.method == 'POST':
        #  html 입력한 값 받아오기
        title = request.form['title']
        price = int(request.form.get('price') or 0)
        discount = request.form.get('discount')
        tags = request.form.get('tags')
        content = request.form.get('description', '내용없음')
        user_id = g.user.id

        #  DB 저장하기
        product = Product(
            title=title,
            content=content,  # content 필수 채움
            price=price,
            discount=discount,
            create_date=datetime.now(),
            tags=tags,
            user_id=user_id
        )
        db.session.add(product)
        db.session.commit()  # db 에 먼저 저장해서 product.id 확보

        files = request.files.getlist('images')  # 여러 이미지 가져오기
        upload_folder = os.path.join(current_app.root_path, 'static/product_img', str(g.user.id))  # 저장할 경로
        os.makedirs(upload_folder, exist_ok=True)  # 경로에 해당하는 파일이 없으면 생성

        for file in files:
            if file and file.filename != '':  # 파일 존재 확인
                filename = file.filename  # 안전한 파일명
                filepath = os.path.join(upload_folder, filename)  # 저장 경로
                file.save(filepath)  # 서버에 파일 저장

                product_image = ProductImage(
                    product_id=product.id,
                    img_path=f'product_img/{g.user.id}/{filename}'  # 저장하면서 경로에 userid추가
                )
                db.session.add(product_image)

        db.session.commit()
        flash('상품 등록 완료!', 'success')
        return redirect(url_for('items._list'))

    return render_template('items/items_form.html')


@bp.route('/detail/<int:product_id>')
def detail(product_id):
    weekday_map = {
        'Mon': '월',
        'Tue': '화',
        'Wed': '수',
        'Thu': '목',
        'Fri': '금',
        'Sat': '토',
        'Sun': '일'
    }
    today = datetime.today()
    arrival_date = datetime.today() + timedelta(days=2)
    today_weekday = weekday_map[today.strftime('%a')]
    weekday = weekday_map[arrival_date.strftime('%a')]
    today_formatted_date = today.strftime(f'%m.%d ({today_weekday})')
    formatted_date = arrival_date.strftime(f'%m.%d ({weekday})')

    products = Product.query.order_by(Product.create_date.desc()).all()
    product = Product.query.get_or_404(product_id)

    return render_template('items/items_detail.html', product=product, products=products, arrival=formatted_date,
                           today=today_formatted_date)


@bp.route('/delete/<int:product_id>')
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)

    # 작성자이거나 관리자이면 삭제 가능
    if g.user.id != product.user_id and not g.user.admin:
        flash('삭제 권한이 없습니다.', 'danger')
        return redirect(url_for('items._list'))

    # 상품 이미지 먼저 삭제
    ProductImage.query.filter_by(product_id=product.id).delete()

    # 상품 삭제
    db.session.delete(product)
    db.session.commit()
    flash('상품이 삭제되었습니다.', 'success')

    return redirect(url_for('member.mypage'))

main/views/member_views.py
import os
from flask import Blueprint, redirect, url_for, render_template, g, request, current_app
from werkzeug.utils import secure_filename

from main import db
# User 모델을 임포트해야 함
from main.models import User, Product
from main.forms import UserCreateForm

bp = Blueprint('member', __name__, url_prefix='/member')


@bp.route('/mypage', methods=['GET', 'POST'])
def mypage():
    form = UserCreateForm()
    page = request.args.get('page', default=1, type=int)  # 페이지
    if g.user.admin:
        product_list = Product.query.order_by(Product.create_date.desc()) \
            .paginate(page=page, per_page=5)
    else:
        product_list = Product.query \
            .filter_by(user_id=g.user.id) \
            .order_by(Product.create_date.desc()) \
            .paginate(page=page, per_page=5)

    if request.method == 'POST':
        formimage = form.image.data
        image = 'user_img/default.jpg'
        if formimage:
            upload_folder = os.path.join(current_app.root_path, 'static/user_img', str(g.user.id))
            os.makedirs(upload_folder, exist_ok=True)
            if g.user.image and g.user.image != 'user_img/default.jpg':
                existing_image_path = os.path.join(current_app.root_path, 'static', g.user.image)
                if os.path.exists(existing_image_path):
                    os.remove(existing_image_path)

            filename = secure_filename(formimage.filename)
            file_path = os.path.join(upload_folder, filename)
            formimage.save(file_path)

            g.user.image = f'user_img/{g.user.id}/{filename}'
            db.session.commit()
        return redirect(url_for('member.mypage'))

    return render_template('member/mypage.html', user=g.user, form=form, page=page, product_list=product_list)


@bp.route('/create', methods=['GET'])
def create():
    return render_template('items/items_form.html')

main/templates/member/mypage.html
{% extends 'base.html' %}
{% block mypage %}

    <link rel="stylesheet" href="{{ url_for('static', filename='mypage/mypage.css') }}">

    {#    <script src="{{ url_for('static', filename='mypage/mypage.js') }}"></script>#}
{% endblock %}
{% block content %}

    <div class="mypage">

        <!-- 마이페이지 최상단  -->
        <div class="top">
            <!-- 자기정보 -->
            <div class="my">
                <!-- 자기사진 -->
                <div class="mytop">
                    <img class="myimg" src="{{ url_for('static', filename=user.image) }}" alt="">
                    <div>
                        <!-- 이미지 업로드 -->
                        <form method="post" action="{{ url_for('member.mypage') }}" enctype="multipart/form-data">

                            {{ form.csrf_token }}

                            <div class="img_url">
                                <label for="image">이미지 첨부</label>
                                <input type="file" name="image" id="image" class="form-control">
                                <button type="submit" class="image_submit">저장하기</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- 닉네임, 연락처 -->
                <div class="mymid">
                    <div class="name">닉네임</div>
                    <div class="name_db">{{ user.username }}</div>
                    <div class="phone">전화번호</div>
                    <div class="phone_db">{{ user.phone }}</div>
                </div>
                <!-- 주소 -->
                <div class="mybottom">
                    <div class="address">주소</div>
                    <div class="address_db"> {{ user.address }}</div>
                </div>
            </div>
            <!-- 등록한 상품기록 -->
            <div class="post">
                <div class="p-move">
                    <!-- 상품등록 이동해 -->
                    <p class="p-title">상품 등록 기록 조회</p>
                    <div class="create"><a href="{{ url_for('member.create') }}">상품 등록</a></div>
                </div>
                {#상품 등록 게시판#}
                <div class="table-wrap">
                    <table class="post-table">
                        <thead>
                        <tr class="post-title">
                            <th scope="col">번호</th>
                            <th scope="col">상품명</th>
                            <th scope="col">가격</th>
                            <th scope="col">등록일</th>
                            {#<th scope="col">조회</th>#}
                            <th scope="col">관리</th>
                        </tr>
                        </thead>
                        <tbody id="productBody">
                        {% if product_list %}
                            {% for product in product_list.items %}

                                <tr>
                                    <td>{{ loop.index0 + 1 }}</td>
                                    <td>{{ product.title }}</td>
                                    <td>{{ "{:,}".format(product.price) }}원</td>
                                    <td>{{ product.create_date.strftime('%y-%m-%d') }}</td>
                                    <td> {% if g.user.admin or product.user_id == g.user.id %}
                                        <button class="btn btn-sm btn-outline-danger delete"
                                                data-uri="{{ url_for('items.delete_product', product_id=product.id) }}">
                                            삭제
                                        </button>
                                        {% endif %}
                                    </td>


                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="4">등록한 상품이 없습니다.</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                    <ul class="pagination justify-content-center">
                        <!--        이전버튼-->
                        {% if product_list.has_prev %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for('member.mypage', page=product_list.prev_num) }}">이전</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">이전</a></li>
                        {% endif %}
                        <!-- 페이지 번호 -->
                        {% for page_num in product_list.iter_pages() %}
                            {% if page_num %}
                                {% if page_num != product_list.page %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ url_for('member.mypage', page=page_num) }}">{{ page_num }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
                                {% endif %}
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">...</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 다음 버튼 -->
                        {% if product_list.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for('member.mypage', page=product_list.next_num) }}">다음</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">다음</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- 댓글기록 -->
        <div class="comment">
            <div class="c-move">
                <p>댓글 기록 조회</p>
            </div>

            <!-- 댓글 게시판 -->
            <div class="comment-table-wrap">
                <table class="comment-table">
                    <thead>
                    <tr>
                        <th>번호</th>
                        <th>댓글 내용</th>
                        <th>작성일</th>
                        <th>상태</th>
                        <th>관리</th>
                    </tr>
                    </thead>
                    <tbody id="commentBody">
                    <tr>
                        <td colspan="5" style="color: #999; text-align: center;padding: 30px">
                            등록된 댓글이 없습니다.
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<script>
    const delete_elements = document.querySelectorAll('.delete');
    delete_elements.forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm('정말로 삭제하시겠습니까?')) {
                location.href = this.dataset.uri;
            }
        })
    })

</script>

{% endblock %}